name: Browser Extension Release

on:
  push:
    tags:
      - '*'

jobs:
  detect-type:
    runs-on: ubuntu-latest
    outputs:
      release_type: ${{ steps.check-type.outputs.release_type }}
    steps:
      - name: Determine Release Type
        id: check-type
        shell: bash
        run: |
          TAG="${GITHUB_REF#refs/tags/}"
          if [[ "$TAG" =~ (beta|rc|alpha) ]]; then
            echo "release_type=prerelease" >> $GITHUB_OUTPUT
          else
            echo "release_type=release" >> $GITHUB_OUTPUT
          fi

  build:
    runs-on: ubuntu-latest
    needs: detect-type
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build Chromium and Firefox Extensions
        run: npx webpack --mode production

      - name: Inject version into manifest files
        run: |
          TAG="${GITHUB_REF#refs/tags/}"
          for browser in chromium firefox; do
            echo "Updating version in dist/$browser/manifest.json"
            jq --arg version "$TAG" '.version = $version' dist/$browser/manifest.json > dist/$browser/manifest.json.tmp
            mv dist/$browser/manifest.json.tmp dist/$browser/manifest.json
          done

      - name: Package Chromium Extension
        run: |
          cd dist/chromium
          zip -r ../../neural-privacy-policy_${{ github.ref_name }}_chromium.zip .

      - name: Package Firefox Extension
        run: |
          cd dist/firefox
          zip -r ../../neural-privacy-policy_${{ github.ref_name }}_firefox.zip .

      - name: Upload Chromium & Firefox Release Assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            neural-privacy-policy_${{ github.ref_name }}_chromium.zip
            neural-privacy-policy_${{ github.ref_name }}_firefox.zip
          prerelease: ${{ needs.detect-type.outputs.release_type == 'prerelease' }}
